AJEOpex/Models/AMCOpex.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AJEOpex.Models
{
    public class AMCOpex
    {

        [ScaffoldColumn(true)]
        public int OA_ID { set; get; }
        public string Description { set; get; }
        public char ItemType { set; get; }
    }
}

AJEOpex/Models/Opex.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AJEOpex.Models
{
    public class Opex
    {
        public int OpexID { set; get; }
        public int BudgetYear { set; get; }
        public string Department { set; get; }

        public List<OpexDetail> lstOpexDetails { get; set; }

    }
}

AJEOpex/Models/OpexDetail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AJEOpex.Models
{
    public class OpexDetail
    {
        public int OpexDetailID { set; get; }
        public int THOpexID { set; get; }
        public int OA_ID { set; get; }
        public Double Actual { set; get; }
        public Double BudgetYTD { set; get; }
        public Double BudgetVar { set; get; }
        public string Comments { set; get; }

    }
}

AJEOpex/Models/ViewModel/OpexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AJEOpex.Models
{
    public class OpexViewModel
    {
        public int OA_ID { set; get; }

        public string Description { set; get; }
        public Double Actual { set; get; }
        public Double BudgetYTD { set; get; }

        public Double BudgetVar { set; get; }

        public string Comments { set; get; }

        public bool ItemSelection { set; get; }
    }


    public class OpexSummaryViewModel
    {
        public int  Sr { set; get; }
        public int OA_ID { set; get; }

        public string Description { set; get; }
        public Double Actual { set; get; }
        public Double BudgetYTD { set; get; }

        public Double BudgetVar { set; get; }

        public string Comments { set; get; }

        
    }

}

AJEOpex/Controllers/AMCOpexController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;

namespace AJEOpex.Controllers
{
    public class AMCOpexController : Controller
    {
        // GET: AMCOpex
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveAMCOpex(string Description)
        {
            int AMCOpexID = 0;
            System.Data.IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
            string sql = " INSERT INTO AMC_Opex(Description,ItemType) " +
                              " VALUES (@Description,'F')" +
                             " SELECT CAST(SCOPE_IDENTITY() as int)";

            AMCOpexID = db.Query<int>(sql, new
            {
                Description
            })
              .SingleOrDefault();
           return Json(AMCOpexID, JsonRequestBehavior.AllowGet);
            
        }

    }
}

AJEOpex/Controllers/BudgetController.cs
using Dapper; 
using AJEOpex.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IT_BP.Controllers
{
    public class BudgetController : Controller
    {
        System.Data.IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        // GET: Budget
        public ActionResult Opex()
        {
            
            var obj1 = db.Query<OpexViewModel>("Select a.OA_ID,a.Description, 0 as Acual, 0 as BudgetYTD, 0 as BudgetVar, '' as Comments  FROM AMC_Opex as a where ItemType = 'F'").ToList();
            db.Close(); 
            return View(obj1);
        }


       [HttpPost]
        public ActionResult SaveOMCOpexBudget(List<OpexViewModel> Model,int BudgetedYear,String Department)
        {
            string sqlDetail="";
            int RecordID = 0;
            string sql = " INSERT INTO TH_Opex(BudgetYear,Department) " +
                              " VALUES (@BudgetedYear,@Department)" +
                             " SELECT CAST(SCOPE_IDENTITY() as int)";

            RecordID = db.Query<int>(sql, new
            {
                BudgetedYear,
                Department
            })
              .SingleOrDefault();

            if (RecordID > 0 )
            {
                foreach (var item in Model)
                {
                    sqlDetail = @"INSERT INTO TD_Opex(THOpexID,OA_ID,Actual,BudgetYTD,BudgetVar,Comments) " +
                                 " VALUES (@RecordID,@OA_ID,@Actual,@BudgetYTD,@BudgetVar,@Comments)";

                    db.Execute(sqlDetail,
                      new
                      {
                          RecordID,
                          item.OA_ID,
                          item.Actual,
                          item.BudgetYTD,
                          item.BudgetVar,
                          item.Comments
                      });
                }
            }
            
           return  RedirectToAction("Dasboard/index");

           // return View();
        }
    }
}

AJEOpex/Controllers/DasboardController.cs
using AJEOpex.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
namespace AJEOpex.Controllers
{
    public class DasboardController : Controller
    {
        System.Data.IDbConnection db = new SqlConnection(ConfigurationManager.ConnectionStrings["cn"].ConnectionString);
        // GET: Dasboard

        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult OpexSummary()
        {

            var obj1 = db.Query<OpexSummaryViewModel>("Select  ROW_NUMBER() OVER(ORDER BY AMC_Opex.Description ASC) AS Sr,TD_Opex.OA_ID,AMC_Opex.Description,TD_Opex.Actual,TD_Opex.BudgetYTD," +
                                                      "TD_Opex.BudgetVar,TD_Opex.Comments" +
                                                      " From TD_Opex inner join AMC_Opex on TD_Opex.OA_ID = AMC_Opex.OA_ID").ToList();
            db.Close();
            return PartialView("_SummOpex",obj1);
        }
    }
}

AJEOpex/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AJEOpex.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AJEOpex/Views/Budget/Opex.cshtml
@model IList<AJEOpex.Models.OpexViewModel>
@using System.Configuration

@{
    ViewBag.Title = "Opex";
    int Rowindex=0;
}
<link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
<script src="~/Scripts/jquery.dataTables.js"></script>

<script type="text/javascript">
    var DetailListVal = null;
    DetailListVal = [];

    function fnOpexMastersave()
    {
      //First Add Record in Opex Master Table then Add in the Html Table 
      $.ajax
          (
          {
              type: "Post",
              url: 'http://localhost:55106/AMCOpex/SaveAMCOpex',
              dataType: "json",
              contentType: 'application/json; charset=utf-8',
              data: JSON.stringify({ 'Description': $('#txtOpex').val() }),
              success: function (response) {
                  if (response > 0) {
                      var table = $("#tblDetail").DataTable();
                      var rowCount = $('#tblDetail tr').length;
                      //alert(rowCount);
                      table.row.add([
                          '<input type=hidden id=OA_ID_' + rowCount + ' value=' + response + ' />',
                          '<input type=checkbox  id=ItemSelection_' + rowCount + ' checked   onclick = "onClickHandler(this,' + rowCount + ')"/>',
                          $('#txtOpex').val(),
                          '<input type=text id=Actual_' + rowCount + ' value=' + $('#txtActual').val() + ' onchange = "CalculateVariation(' + rowCount + ')" />',
                          '<input type=text id=BudgetYTD_' + rowCount + ' value=' + $('#txtBudgetYTD').val() + ' onchange = "CalculateVariation(' + rowCount + ')" />',
                          '<input type=text disabled id=BudgetVar_' + rowCount + ' value=' + $('#txtBudgetVar').val() + ' />',
                          '<textArea rows="2" cols="20" id=Comments_' + rowCount + ' >' + $('#txtComments').val() + '</textArea>',
                      ]).draw();
                  }
                  else
                  {
                      alert("Error while adding recod in AMC_Opex")
                  }
              }
          });
    }
    function onClickHandler(obj,rowIndex)
    {
        if (obj.checked == true) {
            $('#Actual_' + rowIndex).removeAttr("disabled", "disabled");
            $('#BudgetYTD_' + rowIndex).removeAttr("disabled", "disabled");
           // $('#BudgetVar_' + rowIndex).removeAttr("disabled", "disabled");
            $('#Comments_' + rowIndex).removeAttr("disabled", "disabled");
        }
        else
        {
            $('#Actual_' + rowIndex).attr('disabled', 'disabled');
            $('#BudgetYTD_' + rowIndex).attr('disabled', 'disabled');
           // $('#BudgetVar_' + rowIndex).attr('disabled', 'disabled');
            $('#Comments_' + rowIndex).attr('disabled', 'disabled');
            $('#Actual_' + rowIndex).val('');
            $('#BudgetYTD_' + rowIndex).val('');
            $('#BudgetVar_' + rowIndex).val('');
            $('#Comments_' + rowIndex).val('');



        }

    }
    function ItemDetail(OA_ID, Actual, BudgetYTD, BudgetVar, Comments)
    {
        var DetailJason = {
            "OA_ID": OA_ID,
            "Actual" : Actual,
            "BudgetYTD": BudgetYTD,
            "BudgetVar": BudgetVar,
            "Comments": Comments
        }
        return DetailJason;
    } 
   

    function CalculateVariation(rowIndex)
    {
        var Actual = $('#Actual_' + rowIndex).val();
        var BudgetYTD = $('#BudgetYTD_' + rowIndex).val();

        //if (Actual > 0 && BudgetYTD > 0) {
        var variation = ((BudgetYTD - Actual) / Actual) * 100
        $('#BudgetVar_' + rowIndex).val(Math.round(variation));
        if ($('#BudgetVar_' + rowIndex).val() > 0)
        {
            $('#BudgetVar_' + rowIndex).css({ 'color': 'red'});
        }


       // }
      
    }
</script>
<script type="text/javascript">
    $(document).ready(
        function () {
            var table = $("#tblDetail").DataTable(
                {
                    "bPaginate": false,
                    "bFilter": false,
                    "bInfo": false

                }

            ); //Initialise DataTable
            $('#btnNewItem').click
                (
                function () {
                    //if ($("#assign-dialog").dialog("instance") != undefined) {
                      //  $("#assign-dialog").dialog("destroy");
                   // }

                    $('#assign-dialog').dialog({
                        autoOpen: true,
                        width: 400,
                        height: 400,
                        resizable: false,
                        title: 'AMC',
                        modal: true,
                        buttons: [{
                            text: "Save", click: function () {
                                fnOpexMastersave();
                                $(this).dialog("close");
                            }
                        }
                            , { text: "Cancel", click: function () { $(this).dialog("close"); } }
                        ]


                    })
                }
                );

         

        });
</script>

<script>

    function SaveOpex()
    {
            var table = $("#tblDetail").DataTable();
            var rowCount = $('#tblDetail tr').length;
            //debugger;
            var lProcess;
            for (var i = 1; i < rowCount; i++) {
                lProcess = false;
                var obj = document.getElementById("ItemSelection_" + i);
                if (obj.checked == true) {
                    //debugger;
                    var OA_ID = document.getElementById("OA_ID_" + i).value;
                    var Actual = document.getElementById("Actual_" + i).value;
                    var BudgetYTD = document.getElementById("BudgetYTD_" + i).value;
                    var BudgetVar = document.getElementById("BudgetVar_" + i).value;
                    var Comments = document.getElementById("Comments_" + i).value;
                    var objDetail = new ItemDetail(OA_ID, Actual, BudgetYTD, BudgetVar, Comments)
                    
                    DetailListVal.push(objDetail);
                   //  alert(objDetail);
                    // alert(JSON.stringify(objDetail));
                }
            }
            //alert(JSON.stringify(DetailListVal));
            $.ajax
                (
                {

                    type: "Post",
                    url: 'http://localhost:55106/Budget/SaveOMCOpexBudget',
                    dataType: "json",
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify({ 'Model': DetailListVal, 'BudgetedYear': 2017, 'Department': 'IT' }),
                    success: function (response) {
                        alert(response);
                        // window.location.href = '<%:Convert.ToString(ConfigurationManager.AppSettings["Sitepath"])%>' + "Home/index";
                    }
                }
                );

            }

</script>

<h2>Opex</h2>
<input type="button" value="Add New Item" id="btnNewItem" class="btn btn-success" />


 @Html.ActionLink("Save", " ", null,  new { onclick = "return ShowConfirm('Are you sure you want to Save?','Al Jaber Group LLC','c',''  );", @class = "btn btn-success", id = "btnNew" })


    <table class="table">
        <tr>
            <td>Budget Year</td>
            <td><input type="text" name="BudgetYear"/></td>
            <td>Department</td>
            <td><input type="text" name="department"/></td>
        </tr>



    </table>

    <table id="tblDetail" class="table table-striped" >
        <thead>
            <tr>
                <th></th>
                <th></th>
                <th>
                    @Html.DisplayName("Budget Category")
                </th>
                <th>
                    @Html.DisplayName("Actual")
                </th>
                <th>
                    @Html.DisplayName("Budget YTD")
                </th>
                <th>
                    @Html.DisplayName("Var % ")
                </th>
                <th>
                    @Html.DisplayName("Comments")
                </th>
                
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Count; i++)
            {
                Rowindex= i + 1;
                <tr>
                    <td>
                        @Html.Hidden("OA_ID_" + Rowindex, Model[i].OA_ID)
                    </td>
                    <td>
                        @Html.CheckBox("ItemSelection_" + Rowindex, Model[i].ItemSelection,new { onclick = "onClickHandler(this,"+ Rowindex + ")"})
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Description)
                    </td>
                    <td>
                        @Html.TextBox("Actual_"+ Rowindex, Model[i].Actual, new { @disabled = "true", onchange = "CalculateVariation(" + Rowindex + ")" })
                    </td>
                    <td>
                        @Html.TextBox("BudgetYTD_" + Rowindex, Model[i].BudgetYTD, new { @disabled = "true", onchange = "CalculateVariation(" + Rowindex + ")" })
                    </td>
                    <td>
                        @Html.TextBox("BudgetVar_" + Rowindex, Model[i].BudgetVar, new { @disabled = "true" })
                    </td>
                    <td>
                        @Html.TextArea("Comments_" + Rowindex, Model[i].Comments, new { @disabled = "true" })
                    </td>
                </tr>
            }
        </tbody>
    </table>
    



<div id="assign-dialog" style="display:none">
    <table class="table table-striped">
        <tr>
            <td>
                Description
            </td>
            <td>
                <input type="text" id="txtOpex" />
            </td>
        </tr>

        <tr>
            <td>
                Actual
            </td>
            <td>
                <input type="text" id="txtActual" />
            </td>
        </tr>
        <tr>
            <td>
                Budget YTD
            </td>
            <td>
                <input type="text" id="txtBudgetYTD" />
            </td>
        </tr>
        <tr>
            <td>
                Var %
            </td>
            <td>
                <input type="text" id="txtBudgetVar" />
            </td>
        </tr>

        <tr>
            <td>
                Comments
            </td>
            <td>
                <input type="text"  id="txtComments" />
            </td>
        </tr>
    </table>


</div>

AJEOpex/Views/Dasboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
}


        @{Html.RenderAction("OpexSummary", "Dasboard");
        }

AJEOpex/Views/Dasboard/gffff.cshtml
@{
    ViewBag.Title = "gffff";
}

<h2>gffff</h2>

AJEOpex/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AJEOpex/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AJEOpex/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>AJC</h1>
    <p class="lead">AJC</p>
    <p></p>
</div>

<div class="row">
    <div class="col-md-4">
        
        <p>
       
        </p>
        <p></p>
    </div>
    <div class="col-md-4">
        
    </div>
    <div class="col-md-4">
        
    </div>
</div>

AJEOpex/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    
    @Scripts.Render("~/bundles/modernizr")



    <script>
        function ShowConfirm(message, Title, Value, closevalue) {
            $(function () {

                if ($("#dialog").dialog("instance") != undefined) {
                    $("#dialog").dialog("destroy");
                }
                var ErrorType = 'Confirm'
                var imagepath = "/Content/Meassagebox/Icons/" + ErrorType + ".png";

                message = message = "<table colspan='0' cellspacing='0' border='0' width='340px'><tr><td  width='40px'><image src='" + imagepath + "'></image></td><td  width='300px'>" + message + "</td></tr></table>";

                $("#dialog").html(message);
                $("#dialog").dialog(
                    { resizable: false },
                    { width: 400 },
                    {
                        title: Title,
                        buttons: {
                            "Yes": function (e) {
                                e.preventDefault();
                                if (Value.length != 0) {
                                    if (Value == "c") {
                                        SaveOpex();
                                    }
                                    else {
                                        window.location.href = Value;
                                    }

                                }
                                else {
                                    window.location.reload(true);
                                }
                                $(this).dialog("close");
                            }, "No": function () {
                                $(this).dialog("close");
                                if (closevalue != "") {
                                    window.close();
                                    window.location.href = 'http://ajes-inapp/AJESAppraisal';
                                }
                                return false;

                            }
                        },
                        modal: true
                    });
                $(".selector").dialog("option", "closeOnEscape", false);
            });
            return false;
        };



    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AJC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Budget Opex", "Opex", "Budget")</li>
                    <li>@Html.ActionLink("Budget Capex", "About", "Home")</li>
                    <li>@Html.ActionLink("Dashboard", "Index", "Dasboard")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AJC</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    
    @RenderSection("scripts", required: false)
    <div id="dialog" style="display: none"></div>
</body>
</html>

AJEOpex/Views/Shared/_SummOpex.cshtml
@model IEnumerable<AJEOpex.Models.OpexSummaryViewModel>
<h2>Opex Summary</h2>
<table class="table table-hover">
    <tr>
        <th>
            Sr.
        </th>
        <th>
            Budget Category
        </th>
        <th>
            Actual
        </th>
        <th>
           Budget YTD
        </th>
        <th>
            Var % 
        </th>
        <th>
            Comments
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            
            @Html.DisplayFor(modelItem => item.Sr)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Actual)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BudgetYTD)
        </td>
        <td>
            @if (item.BudgetVar > 0)
            {
                
                @Html.DisplayFor(modelItem => item.BudgetVar)
            }
            else
            { @Html.DisplayFor(modelItem => item.BudgetVar)
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
      
    </tr>
}

</table>